// Code generated by "stringer -type Op"; DO NOT EDIT.

package ossa

import "strconv"

const _Op_name = "opInvalidOpGlobalSymOpLocalSymOpArgumentOpAuxLiteralOpPhiOpLoadOpStoreOpCallopBasicBlockopEndValuesOpJumpOpBranchOpSwitchOpReturnOpYieldOpAwaitOpUnreachableopEndTerminators"

var _Op_index = [...]uint8{0, 9, 20, 30, 40, 52, 57, 63, 70, 76, 88, 99, 105, 113, 121, 129, 136, 143, 156, 172}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
